name: Deploy Rust Koois Auth

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: cargo build --release

      - name: Verify binary exists
        run: ls -lh target/release/

      - name: Deploy binary to VPS via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT || '22' }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: target/release/koois_auth
          target: /home/deploy/backend/git_action/

      - name: Restart systemd service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT || '22' }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            echo ">>> Setting permissions..."
            chmod +x /home/deploy/backend/git_action/koois_auth

            echo ">>> Restarting systemd service..."
            sudo systemctl restart koois_auth
            sudo systemctl status koois_auth --no-pager -l

            echo ">>> ✅ Deployment complete!"
